=== scanlime/navi-misc/trunk/sxmadb/schema.xsd
<?xml version="1.0"?>
<xsd:schema
 xmlns:xsd="http://www.w3.org/2001/XMLSchema"
 xmlns:xi="http://www.w3.org/2003/XInclude">

<xsd:simpleType name="side">
  <xsd:restriction base="xsd:string">
    <xsd:enumeration value="right"/>
    <xsd:enumeration value="left"/>
  </xsd:restriction>
</xsd:simpleType>

<!-- =============== movement -->
<xsd:simpleType name="movement-stance">
  <xsd:restriction base="xsd:string">
    <xsd:enumeration value="attention"/>
    <xsd:enumeration value="natural"/>
    <xsd:enumeration value="horse"/>
    <xsd:enumeration value="neutral bow"/>
    <xsd:enumeration value="forward bow"/>
    <xsd:enumeration value="cat"/>
    <xsd:enumeration value="reverse bow"/>
    <xsd:enumeration value="close kneel"/>
    <xsd:enumeration value="wide kneel"/>
    <xsd:enumeration value="front twist"/>
    <xsd:enumeration value="rear twist"/>
    <xsd:enumeration value="reverse close kneel"/>
    <xsd:enumeration value="reverse wide kneel"/>
    <xsd:enumeration value="concave"/>
    <xsd:enumeration value="diamond"/>
  </xsd:restriction>
</xsd:simpleType>

<xsd:simpleType name="movement-block">
  <xsd:restriction base="xsd:string">
    <xsd:enumeration value="hammering inward"/>
    <xsd:enumeration value="thrusting inward"/>
    <xsd:enumeration value="vertical outward"/>
    <xsd:enumeration value="extended outward"/>
    <xsd:enumeration value="upward"/>
    <xsd:enumeration value="downward"/>
    <xsd:enumeration value="palm heel"/>
    <xsd:enumeration value="inward downward palm up"/>
    <xsd:enumeration value="inward downward palm down"/>
    <xsd:enumeration value="cross"/>
    <xsd:enumeration value="universal"/>
    <xsd:enumeration value="outward downward diagonal"/>
    <xsd:enumeration value="downward horizontal forearm"/>
    <xsd:enumeration value="inward vertical forearm"/>
    <xsd:enumeration value="outward vertical forearm"/>
  </xsd:restriction>
</xsd:simpleType>

<xsd:simpleType name="movement-footManeuver">
  <xsd:restriction base="xsd:string">
    <xsd:enumeration value="drag-step"/>
    <xsd:enumeration value="step-drag"/>
    <xsd:enumeration value="step-through"/>
    <xsd:enumeration value="rear cover"/>
    <xsd:enumeration value="side cover"/>
    <xsd:enumeration value="push step-drag"/>
    <xsd:enumeration value="front crossover"/>
    <xsd:enumeration value="rear crossover"/>
    <xsd:enumeration value="hop"/>
    <xsd:enumeration value="pull-drag"/>
    <xsd:enumeration value="leap"/>
    <xsd:enumeration value="step"/>
    <xsd:enumeration value="step back"/>
    <xsd:enumeration value="pivot"/>
  </xsd:restriction>
</xsd:simpleType>

<xsd:simpleType name="movement-kick">
  <xsd:restriction base="xsd:string">
    <xsd:enumeration value="front snap"/>
    <xsd:enumeration value="side thrust"/>
    <xsd:enumeration value="back snapping heel"/>
    <xsd:enumeration value="roundhouse"/>
    <xsd:enumeration value="knife-edge side"/>
    <xsd:enumeration value="back thrust"/>
    <xsd:enumeration value="jump front"/>
    <xsd:enumeration value="hop front"/>
    <xsd:enumeration value="wheel"/>
    <xsd:enumeration value="downward looping roundhouse"/>
    <xsd:enumeration value="jump roundhouse"/>
    <xsd:enumeration value="hop roundhouse"/>
    <xsd:enumeration value="inward crescent"/>
    <xsd:enumeration value="outward crescent"/>
    <xsd:enumeration value="spin hook"/>
    <xsd:enumeration value="spin roundhouse"/>
    <xsd:enumeration value="jump spin side"/>
    <xsd:enumeration value="jump spin hook"/>
    <xsd:enumeration value="spin crescent"/>
    <xsd:enumeration value="inward axe"/>
    <xsd:enumeration value="outward axe"/>
    <xsd:enumeration value="jump side"/>
    <xsd:enumeration value="hook"/>
    <xsd:enumeration value="twist"/>
    <xsd:enumeration value="scoop"/>
    <xsd:enumeration value="linear axe"/>
    <xsd:enumeration value="front stomp"/>
    <xsd:enumeration value="side stomp"/>
    <xsd:enumeration value="rear stomp"/>
    <xsd:enumeration value="front chicken"/>
    <xsd:enumeration value="back chicken"/>
    <xsd:enumeration value="spin side"/>
    <xsd:enumeration value="tornado roundhouse"/>
    <xsd:enumeration value="ball roundhouse"/>
  </xsd:restriction>
</xsd:simpleType>

<xsd:simpleType name="movement-parry">
  <xsd:restriction base="xsd:string">
    <xsd:enumeration value="inward"/>
    <xsd:enumeration value="outward"/>
    <xsd:enumeration value="inward downward"/>
    <xsd:enumeration value="outward downward"/>
    <xsd:enumeration value="inward horizontal palm heel"/>
    <xsd:enumeration value="outward horizontal palm heel"/>
    <xsd:enumeration value="upward"/>
    <xsd:enumeration value="inward knee"/>
    <xsd:enumeration value="outward knee"/>
  </xsd:restriction>
</xsd:simpleType>

<xsd:simpleType name="movement-knee">
  <xsd:restriction base="xsd:string">
    <xsd:enumeration value="vertical"/>
    <xsd:enumeration value="hop vertical"/>
  </xsd:restriction>
</xsd:simpleType>

<!-- =============== types for technique -->
<xsd:simpleType name="technique-category">
  <xsd:restriction base="xsd:string">
    <xsd:enumeration value="punch"/>
    <xsd:enumeration value="push"/>
    <xsd:enumeration value="kick"/>
    <xsd:enumeration value="hugs-and-holds"/>
    <xsd:enumeration value="chokes-and-locks"/>
    <xsd:enumeration value="weapons"/>
    <xsd:enumeration value="multiple-attacks"/>
    <xsd:enumeration value="grabs-and-tackles"/>
    <xsd:enumeration value="combination"/>
  </xsd:restriction>
</xsd:simpleType>

<xsd:simpleType name="technique-level">
  <xsd:restriction base="xsd:string">
    <xsd:enumeration value="yellow"/>
    <xsd:enumeration value="orange"/>
    <xsd:enumeration value="purple"/>
    <xsd:enumeration value="blue"/>
    <xsd:enumeration value="green"/>
    <xsd:enumeration value="first-brown"/>
    <xsd:enumeration value="second-brown"/>
    <xsd:enumeration value="third-brown"/>
    <xsd:enumeration value="first-black"/>
    <xsd:enumeration value="second-black"/>
    <xsd:enumeration value="third-black"/>
  </xsd:restriction>
</xsd:simpleType>

<xsd:complexType name="technique-stances">
  <xsd:sequence>
    <xsd:element name="attacker" minOccurs="0"/>
    <xsd:element name="defender" minOccurs="0"/>
  </xsd:sequence>
</xsd:complexType>

<xsd:complexType name="technique-step" mixed="true">
  <xsd:choice maxOccurs="unbounded" minOccurs="0">
    <xsd:element name="footManeuver" type="movement-footManeuver"/>
    <xsd:element name="stance" type="movement-stance"/>
    <xsd:element name="block" type="movement-block"/>
    <xsd:element name="kick" type="movement-kick"/>
    <xsd:element name="parry" type="movement-parry"/>
    <xsd:element name="knee" type="movement-knee"/>
    <xsd:element name="strike"/>
  </xsd:choice>
</xsd:complexType>

<xsd:complexType name="technique-steps">
  <xsd:sequence>
    <xsd:element name="step" type="technique-step" maxOccurs="200"/>
  </xsd:sequence>
</xsd:complexType>

<xsd:complexType name="technique-notes">
  <xsd:sequence>
    <xsd:element name="note" type="xsd:string"/>
  </xsd:sequence>
</xsd:complexType>

<!-- =============== top-level technique -->
<xsd:element name="technique">
  <xsd:complexType>
    <xsd:all>
      <xsd:element name="attack" type="xsd:string"/>
      <xsd:element name="stances" type="technique-stances" minOccurs="0"/>
      <xsd:element name="steps" type="technique-steps"/>
      <xsd:element name="notes" type="technique-notes" minOccurs="0"/>
    </xsd:all>
    <xsd:attribute name="name" type="xsd:string"/>
    <xsd:attribute name="level" type="technique-level"/>
    <xsd:attribute name="category" type="technique-category"/>
  </xsd:complexType>
</xsd:element>

<!-- =============== types for concept -->
<xsd:complexType name="concept-technique" mixed="true">
  <xsd:sequence>
    <xsd:element name="note" type="xsd:string" minOccurs="0"/>
  </xsd:sequence>
</xsd:complexType>

<xsd:complexType name="concept-techniques">
  <xsd:sequence>
    <xsd:element name="technique" type="concept-technique" maxOccurs="20"/>
  </xsd:sequence>
</xsd:complexType>

<!-- =============== top-level concept -->
<xsd:element name="concept">
  <xsd:complexType>
    <xsd:all>
      <xsd:element name="origin" type="xsd:string" minOccurs="0"/>
      <xsd:element name="overview" type="xsd:string"/>
      <xsd:element name="techniques" type="concept-techniques"/>
    </xsd:all>
    <xsd:attribute name="name" type="xsd:string"/>
  </xsd:complexType>
</xsd:element>

</xsd:schema>

=== scanlime/navi-misc/trunk/sxmadb/techniques/passing-the-horizon.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="../style.xsl"?>

<technique name="passing the horizon" category="chokes-and-locks"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="schema.xsd">
  <attack>rear right-arm hammer lock with a left hand wrist grab</attack>
  <stances>
    <attacker><stance>natural</stance></attacker>
    <defender><stance>natural</stance></defender>
  </stances>
  <steps>
    <step>
      Regrab your opponent's right wrist with your right hand.
      <footManeuver side="left">step back</footManeuver> toward 6:00 into a
      <stance side="right">forward bow</stance> as you thrust your left hand forward
      releasing from the wrist grab.
    </step>
    <step>
      <footManeuver>pivot</footManeuver> into a <stance side="right">neutral bow</stance>
      as you execute a <strike side="left">outward elbow</strike> to your opponent's face.
    </step>
    <step>
      <footManeuver side="left">step</footManeuver> toward 1:30 into a
      <stance side="right">neutral bow</stance> as you rotate your opponent's right wrist
      to the right (clockwise), bending him forward.
    </step>
    <step>
      Execute a <kick side="left">front snap</kick> to your opponent's ribs.
    </step>
  </steps>
</technique>

=== scanlime/navi-misc/trunk/sxmadb/techniques/swinging-pendulum.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="../style.xsl"?>

<technique name="swinging pendulum" level="purple" category="kick"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="schema.xsd">
  <attack>right step-through roundhouse kick</attack>
  <stances>
    <attacker><stance side="left">neutral bow</stance></attacker>
    <defender><stance side="right">neutral bow</stance></defender>
  </stances>
  <steps>
    <step>
      <footManeuver>reverse rear cover</footManeuver> toward 5:30 into a
      <stance side="right">neutral bow</stance> as you execute a
      <block side="right">universal</block> above your opponent's right knee.
    </step>
    <step>
      <footManeuver>step-drag</footManeuver> toward 10:30 into a
      <stance side="right">neutral bow</stance> as you execute a
      <strike side="right">outward downward hammer fist</strike> to your opponent's
      groin.
    </step>
    <step>
      <footManeuver side="left">step</footManeuver> toward 3:00 into a
      <stance side="right">neutral bow</stance> (moving up the circle) as you execute
      a <strike side="right">obscure elbow</strike> to your opponent's chin.
    </step>
  </steps>
</technique>

=== scanlime/navi-misc/trunk/sxmadb/techniques/repeating-mace.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="../style.xsl"?>

<technique name="repeating mace" level="orange" category="push"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="schema.xsd">
  <attack>left step-through cross push</attack>
  <stances>
    <attacker><stance side="right">neutral bow</stance></attacker>
    <defender><stance>natural</stance></defender>
  </stances>
  <steps>
    <step>
      <footManeuver side="left">step back</footManeuver> toward 6:00 into a
      <stance side="right">forward bow</stance> as you execute a
      <parry side="left">outward</parry> to the outside of your opponent's left arm.
    </step>
    <step>
      <footManeuver>pivot</footManeuver> into a <stance side="right">neutral bow</stance>
      as you execute a <strike side="right">inward diagonal hammer fist</strike> to your
      opponent's left kidney.
    </step>
    <step>
      <footManeuver>pivot</footManeuver> into a <stance side="right">forward bow</stance>
      as you execute a <punch side="right">outward back knuckle</punch> to your
      opponent's left ribs.
    </step>
    <step>
      Draw your left foot toward your right into a <stance side="right">cat</stance>
      stance.
    </step>
    <step>
      Execute a <kick side="right">downward looping roundhouse</kick> to the top of
      your opponent's left calf.
    </step>
  </steps>
</technique>

=== scanlime/navi-misc/trunk/sxmadb/techniques/intellectual-departure.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="../style.xsl"?>

<technique name="intellectual departure" category="kick"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="schema.xsd">
  <attack>right step through front snap kick</attack>
  <stances>
    <attacker>left neutral bow</attacker>
    <defender>natural</defender>
  </stances>
  <steps>
    <step>
      <footManeuver side="left">step back</footManeuver> toward 4:30 into a
      <stance side="right">close kneel</stance> as you execute a right
      <block side="right">inward downward palm down</block> to your
      opponent's right foreleg.
    </step>
    <step>
      Execute a <kick side="right">back thrust</kick> to your
      opponent's mid section.
    </step>
  </steps>
</technique>
